[package]
name = "catch"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
env_logger = "0.11.8"
ion = { git = "https://github.com/alshdavid/ion.git", version = "0.2.0" }
log = "0.4.29"
maud = { version = "0.27.0", features = ["actix-web"] }
serde_json = "1.0.149"
